using System;
using System.Collections.Generic;
using System.Text;

namespace WebApi.Definition.Model
{
    /// <summary>
    /// Trace and exception information generated by plug-ins and custom workflow activities.
    /// </summary>
    /// <see href="https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/plugintracelog?view=dynamics-ce-odata-9"/>
    public class PluginTraceLogs
    {
        public string ODataContext { get; set; }
        /// <summary>
        /// Unsecured configuration for the plug-in trace log.
        /// </summary>
        public string configuration { get; set; }
        public string correlationid { get; set; }
        public DateTime createdon { get; set; }
        public int depth { get; set; }
        public string exceptiondetails { get; set; }
        public bool issystemcreated { get; set; }
        public string messageblock { get; set; }
        public string messagename { get; set; }
        public Enum.ExecutionType mode { get; set; }
        public Enum.OperationType operationtype { get; set; }
        public Guid organizationid { get; set; }
        public int performanceconstructorduration { get; set; }
        public DateTime perforanceconstructorstarttime { get; set; }
        public int performanceexecutionduration { get; set; }
        public DateTime performanceexecutionstarttime { get; set; }
        public Guid persistencekey { get; set; }
        public Guid pluginstepid { get; set; }
        public Guid plugintracelogid { get; set; }
        public string primaryentity { get; set; }
        public string profile { get; set; }
        /// <summary>
        /// Unique identifier of the message request.
        // Display Name: Request ID
        //Read Only
        /// </summary>
        public Guid requestid { get; set; }
        /// <summary>
        /// Secured configuration for the plug-in trace log.
        /// Display Name: Secure Configuration
        /// Read Only
        /// </summary>
        public string secureconfiguration { get; set; }
        /// <summary>
        /// Class name of the plug-in.
        /// Display Name: Type Name
        /// Read Only
        /// </summary>
        public string typename { get; set; }
    }
}
