using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using WebApi_ADAL.Definition.Enum;

namespace WebApi_ADAL.Definition.Model
{
    /// <summary>
    /// Trace and exception information generated by plug-ins and custom workflow activities.
    /// </summary>
    /// <see href="https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/plugintracelog?view=dynamics-ce-odata-9"/>
    public class PluginTraceLogs
    {
        [JsonPropertyName("@odata.context")]
        public string OdataContext { get; set; }
        /// <summary>
        /// Unsecured configuration for the plug-in trace log.
        /// </summary>
        public string configuration { get; set; }
        public string correlationid { get; set; }
        public DateTime createdon { get; set; }
        public int depth { get; set; }
        public string exceptiondetails { get; set; }
        public bool issystemcreated { get; set; }
        public string messageblock { get; set; }
        public string messagename { get; set; }
        public ExecutionType mode { get; set; }
        public OperationType operationtype { get; set; }
        public Guid organizationid { get; set; }
        public int performanceconstructorduration { get; set; }
        public DateTime perforanceconstructorstarttime { get; set; }
        public int performanceexecutionduration { get; set; }
        public DateTime performanceexecutionstarttime { get; set; }
        public Guid persistencekey { get; set; }
        public Guid pluginstepid { get; set; }
        public Guid plugintracelogid { get; set; }
        public string primaryentity { get; set; }
        public string profile { get; set; }
        /// <summary>
        /// Unique identifier of the message request.
        /// Display Name: Request ID
        //Read Only
        /// </summary>
        [JsonPropertyName("requestid")]
        public Guid RequestId { get; set; }
        /// <summary>
        /// Secured configuration for the plug-in trace log.
        /// Display Name: Secure Configuration
        /// Read Only
        /// </summary>
        public string secureconfiguration { get; set; }
        /// <summary>
        /// Class name of the plug-in.
        /// Display Name: Type Name
        /// Read Only
        /// </summary>
        public string typename { get; set; }
    }
}

/*
 {
  "@odata.context": "https://trueinfo.crm5.dynamics.com/api/data/v9.0/$metadata#plugintracelogs",
  "value": [
    {
      "organizationid": "4ae824f9-043d-41be-82f3-a17efbee4b26",
      "requestid": "7492bf46-3d23-47e7-b03b-04331a94508b",
      "operationtype": 2,
      "primaryentity": "email",
      "correlationid": "d66d2743-3a0e-432d-b346-8d75e3fb4cca",
      "performanceexecutionduration": 1562,
      "_createdby_value": "cfdcf93a-2310-4ef5-99f3-f20d72a8b76f",
      "configuration": "",
      "issystemcreated": true,
      "messageblock": "InitiatingUserId :: 820b2549-3fb9-e811-a97a-000d3aa2e337\r\nInside RetrieveEntityConfiguration : \r\nInside email\r\nInside RetrieveEntityConfiguration :  fetchXML <fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' top='1' no-lock='true' >\r\n                <entity name='ikl_entityconfiguration' >\r\n                <attribute name='ikl_entityname' />\r\n                <filter>\r\n                <condition attribute='ikl_entityname' operator='eq' value='email' />\r\n                <condition attribute='ikl_automoveattachments' operator='not-null' />\r\n                <condition attribute='statecode' operator='eq' value='0' />\r\n                </filter>\r\n                <link-entity name='ikl_connector' from='ikl_connectorid' to='ikl_connector' link-type='inner' alias='conn' >\r\n                <attribute name='ikl_connectorid' />\r\n                <filter>\r\n                <condition attribute='statecode' operator='eq' value='0' />\r\n                </filter>\r\n                </link-entity>\r\n                </entity>\r\n                </fetch>",
      "secureconfiguration": "",
      "messagename": "Create",
      "performanceconstructorstarttime": "2023-01-30T00:38:47.277Z",
      "depth": 2,
      "plugintracelogid": "1efcf7ae-8250-46e0-a6fe-2333c5aecbd1",
      "mode": 1,
      "performanceexecutionstarttime": "2023-01-30T00:38:47.277Z",
      "exceptiondetails": "",
      "typename": "Inogic.Attach2Dynamics.WorkFlows.CheckEmailEntityConfigurationExistOrNot, Inogic.Attach2Dynamics.WorkFlows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=2d42835a1a09de1a",
      "pluginstepid": "a07509cc-ead1-ec11-a7b5-000d3aa357c4",
      "persistencekey": "00000000-0000-0000-0000-000000000000",
      "createdon": "2023-01-30T00:39:10Z",
      "performanceconstructorduration": 0,
      "_createdonbehalfby_value": null,
      "profile": null
    },
  ]
}
*/